sudo: false
services:
    - mongodb
before_script:
    - sleep 15
script: coverage run --source=auth -m pytest -vs tests.py
language: python
python:
    - 2.7
    - pypy
    - 3.3
    - 3.4
    - 3.5
    - pypy3

before_install:
  - pip install codecov
  - pip install -r dev_requirements.txt
after_success:
  - coverage report -m
  - codecov
